name: CI API

permissions:
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - ".github/workflows/ci-api.yml"
      - ".golangci.yml"
      - "go.work"
      - "go.work.sum"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "services/api/**"
      - "turbo.json"
      - "flake.lock"
      - "flake.nix"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-api.yml"
      - ".golangci.yml"
      - "go.work"
      - "go.work.sum"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "services/api/**"
      - "turbo.json"
      - "flake.lock"
      - "flake.nix"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3

      - name: Install dependencies
        run: nix develop -c pnpm install --frozen-lockfile

      - name: Format
        run: nix develop -c pnpm --filter @lang-war/api format:check

      - name: Lint
        run: nix develop -c pnpm --filter @lang-war/api lint

      - name: Test
        run: nix develop -c pnpm --filter @lang-war/api test

      - name: Build
        run: nix develop -c pnpm --filter @lang-war/api build
