name: CI Infra

permissions:
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - ".github/workflows/ci-infra.yml"
      - "flake.lock"
      - "flake.nix"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-infra.yml"
      - "flake.lock"
      - "flake.nix"

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3

      - name: Check flake
        run: nix flake check
